vich_uploader:
  db_driver: orm
  mappings:
    user_cv:
      uri_prefix: /uploads/cv
      upload_destination: "%kernel.project_dir%/public/uploads/cv"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_remove: true
      delete_on_update: true
